### ISSUE TITLE
Migrate Package.swift to swift-tools-version:4.0

### ISSUE THREAD

**Issue by petrpavlik** [petrpavlik/GeoSwift#6]

**Comment by zeusent** [comment]
Hey! Any idea if you have the time to update the file? I came across your little library and it looks really useful but I can't install it. I get this error:
> GeoSwift' is using Swift tools version 3.1.0 which is no longer supported; use 4.0.0 or newer instead

**Comment by petrpavlik** [comment]
@zeusent I  just migrated this repo to Swift 5 so can you try again please?
